-- SECURITY FIX: Enable Row Level Security (RLS) on all tables
-- This is necessary because Supabase exposes all tables via the PostgREST API by default.
-- Without RLS, the public (anon) role might have access to these tables.
-- Enabling RLS without adding policies effectively blocks all public API access, 
-- which is what we want since we are using Prisma (server-side) for all data access.

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SystemSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CloudAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Project" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Booking" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Plan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Feature" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlanFeature" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ScenaProject" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectInvitation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Column" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Task" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Filter" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OAuthAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExternalVideo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CollaborativeGallery" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "QrSection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CollaborativeUpload" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FeatureOverrideLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AdminActionLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CalendarAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExternalCalendarEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CalendarSyncLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StripeConnectAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NoteMention" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReferralProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReferralAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Referral" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReferralCommission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReferralPayout" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReferralAuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReferralClick" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_TaskAssignees" ENABLE ROW LEVEL SECURITY;
