-- Create a table to log keepalive executions
create table if not exists public.keepalive_log (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'executed'
);

-- Enable RLS (optional, but good practice)
alter table public.keepalive_log enable row level security;

-- Create policy to allow anonymous read/write (since script uses anon key usually, or service_role)
-- If using service_role key, RLS is bypassed. If using anon, we need policies.
-- Assuming the script might use anon key for simplicity, or we can use service_role.
-- Let's create a policy just in case.
create policy "Enable insert for everyone" on public.keepalive_log for insert with check (true);
create policy "Enable read for everyone" on public.keepalive_log for select using (true);
